version: "3"
services:
  bot_template:
    image: bot_template
    build:
      context: .
      target: bot_template
      dockerfile: 'BOT_TEMPLATE/Dockerfile'
    container_name: 'BOT_TEMPLATE'
    ports:
      - '1050:1050'
    restart: always
    healthcheck:
      test: ["CMD", "perl", "healthcheck.pl", "", "healthchecker", "--botname", "flujo_recover_actual_d", "--port", "1050"]
      interval: 60s
      retries: 3
      start_period: 10s
      timeout: 2s